basyx:
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
spring:
  data:
    mongodb:
      database: supplier-aas-registry
      uri: mongodb://mongoAdmin:mongoPassword@mongo:27017
